import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Asset, ComplianceItem, InspectionRecord, DefectRecord } from './types';

const generateHeaderAndFooter = (doc: jsPDF, title: string, generatedBy: string) => {
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42); // ink
  doc.text(title, 14, 22);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // steel
  doc.text('OPS GATE', pageWidth - 14, 22, { align: 'right' });
  doc.text(`Generated by: ${generatedBy}`, 14, 30);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 14, 30, { align: 'right' });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184); // steelLight
    doc.text(`Generated by OPS GATE`, 14, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 10, { align: 'right' });
  }
};

export const generateComplianceReport = (assets: Asset[], complianceItems: ComplianceItem[], generatedBy: string): void => {
  const doc = new jsPDF('landscape');
  
  // Summary Stats
  const totalAssets = assets.length;
  const expiredCount = complianceItems.filter(item => item.status === 'expired').length;
  const criticalCount = complianceItems.filter(item => item.status === 'critical').length;
  
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(`Total Assets: ${totalAssets} | Expired Items: ${expiredCount} | Critical Items: ${criticalCount}`, 14, 40);

  const tableData = assets.map(asset => {
    const assetItems = complianceItems.filter(ci => ci.asset_name === asset.name);
    const expired = assetItems.filter(ci => ci.status === 'expired').length;
    return [
      asset.name,
      asset.registration || 'N/A',
      asset.status,
      assetItems.length.toString(),
      expired.toString()
    ];
  });

  autoTable(doc, {
    startY: 45,
    head: [['Asset Name', 'Registration', 'Status', 'Documents Due', 'Expired Count']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [15, 23, 42], textColor: 255 },
    styles: { fontSize: 10, cellPadding: 3 },
  });

  generateHeaderAndFooter(doc, 'Fleet Compliance Summary Report', generatedBy);
  doc.save('compliance-report.pdf');
};

export const generateInspectionReport = (inspections: InspectionRecord[], dateRange: {from: string, to: string}, generatedBy: string): void => {
  const doc = new jsPDF('landscape');

  const total = inspections.length;
  const passed = inspections.filter(i => i.status === 'accepted').length;
  const passRate = total > 0 ? Math.round((passed / total) * 100) : 0;
  const overrideCount = inspections.filter(i => !!i.supervisor_override_by).length;

  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(`Date Range: ${dateRange.from} to ${dateRange.to}`, 14, 40);
  doc.text(`Total Inspections: ${total} | Pass Rate: ${passRate}% | Overrides: ${overrideCount}`, 14, 46);

  const tableData = inspections.map(i => [
    new Date(i.created_at).toLocaleDateString(),
    i.asset_name,
    i.operator_name,
    i.type === 'pre_use' ? 'Pre-Use' : 'Post-Use',
    i.status === 'accepted' ? 'Pass' : 'Fail',
    i.supervisor_override_by ? 'Yes' : 'No'
  ]);

  autoTable(doc, {
    startY: 52,
    head: [['Date', 'Asset', 'Operator', 'Type', 'Result', 'Override']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [15, 23, 42], textColor: 255 },
    styles: { fontSize: 10, cellPadding: 3 },
  });

  generateHeaderAndFooter(doc, 'Inspection History Report', generatedBy);
  doc.save('inspection-report.pdf');
};

export const generateDefectReport = (defects: DefectRecord[], dateRange: {from: string, to: string}, generatedBy: string): void => {
  const doc = new jsPDF('landscape');

  const total = defects.length;
  const openCount = defects.filter(d => d.status === 'open').length;
  const resolvedCount = defects.filter(d => d.status === 'resolved').length;
  
  let totalResolveTimeMs = 0;
  let resolvedWithTimeCount = 0;
  defects.forEach(d => {
    if (d.status === 'resolved' && d.resolved_at) {
      const created = new Date(d.created_at).getTime();
      const resolved = new Date(d.resolved_at).getTime();
      totalResolveTimeMs += (resolved - created);
      resolvedWithTimeCount++;
    }
  });
  const mttrHours = resolvedWithTimeCount > 0 ? (totalResolveTimeMs / resolvedWithTimeCount / (1000 * 60 * 60)).toFixed(1) : 'N/A';

  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(`Date Range: ${dateRange.from} to ${dateRange.to}`, 14, 40);
  doc.text(`Total Defects: ${total} | Open: ${openCount} | Resolved: ${resolvedCount} | MTTR: ${mttrHours} hrs`, 14, 46);

  const tableData = defects.map(d => {
    let resTime = 'N/A';
    if (d.status === 'resolved' && d.resolved_at) {
      const hours = (new Date(d.resolved_at).getTime() - new Date(d.created_at).getTime()) / (1000 * 60 * 60);
      resTime = `${hours.toFixed(1)} hrs`;
    }
    return [
      new Date(d.created_at).toLocaleDateString(),
      d.asset_name,
      d.item_label,
      d.description,
      d.status === 'resolved' ? 'Resolved' : 'Open',
      d.assigned_to || 'Unassigned',
      resTime
    ];
  });

  autoTable(doc, {
    startY: 52,
    head: [['Date', 'Asset', 'Item', 'Description', 'Status', 'Assigned To', 'Resolution Time']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [15, 23, 42], textColor: 255 },
    styles: { fontSize: 10, cellPadding: 3 },
  });

  generateHeaderAndFooter(doc, 'Defect Log Report', generatedBy);
  doc.save('defect-report.pdf');
};
